version: '3'

services:
  web:
    build:
      context: .
    container_name: my-php-web
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: vuln-db
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: myweb1
    volumes:
      - mysql-data:/var/lib/mysql
      - ./myweb1dump.sql:/docker-entrypoint-initdb.d/myweb1dump.sql
volumes:
  mysql-data: